# Environment Variable Setting
################################################################################
dotenv_path: .env  # 从.env文件加载环境变量

# API Provider Setting
################################################################################
api_provider: openai  # 可选值: azure_openai, openai

# Logging Setting
################################################################################
log_dir: logs/hotpotqa/aot_pike  # 日志目录
log_level: INFO  # 日志级别

# Experiment Setting
################################################################################
experiment_name: aot_pike_ablation
test_jsonl_filename: null  # 如果为null，则使用experiment_name
test_rounds: 5  # 每个配置运行5轮以获得统计显著性

# Metadata Setting
################################################################################
metadata:
  task: hotpotqa
  model: aot_pike
  description: "AoT-PIKE完整版本，包含所有功能"

# Azure OpenAI Setting (当 api_provider 为 azure_openai 时使用)
################################################################################
azure_openai:
  api_key: ${AZURE_OPENAI_API_KEY}
  api_base: ${AZURE_OPENAI_API_BASE}
  api_version: "2024-02-15-preview"
  deployment_name: ${AZURE_OPENAI_DEPLOYMENT_NAME}
  embedding_deployment_name: ${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}

# OpenAI Setting (当 api_provider 为 openai 时使用)
################################################################################
openai:
  api_key: ${OPENAI_API_KEY}
  api_base: ${OPENAI_API_BASE}
  model_name: ${OPENAI_MODEL_NAME}
  embedding_model_name: ${OPENAI_EMBEDDING_MODEL_NAME}


# Workflow Setting
################################################################################
workflow:
  module_path: pikerag.workflows
  class_name: AoTPikeWorkflow
  args:
    max_iterations: 5  # 最大迭代次数
    max_dag_depth: 3   # DAG最大深度
    
    # 记忆机制配置（消融实验选项）
    enable_memory: true
    memory_buffer_size: 3
    memory_weight_decay: 0.8
    
    # 集成决策机制配置（消融实验选项）
    enable_ensemble: true
    ensemble_methods: ["direct", "decompose", "contract"]
    
    # 重试机制配置（消融实验选项）
    enable_retry: true
    max_retries: 3
    retry_delay: 1.0
    
    # 并行处理配置（消融实验选项）
    enable_parallel: true
    max_parallel_nodes: 5
    
    # 插件模式配置（消融实验选项）
    enable_plugin_mode: false
    plugin_samples: 3


# Testing Suite Setting
################################################################################
test_loading:
  module: pikerag.utils.data_protocol_utils
  name: load_testing_suite
  args:
    filepath: data/hotpotqa/dev_500.jsonl


# Prompt Setting
################################################################################
# 添加QA协议配置（解决KeyError: 'qa_protocol'问题）
qa_protocol:
  module_path: pikerag.prompts.qa
  attr_name: generation_qa_protocol
  template_partial:
    system_prompt: "你是一个擅长回答问题的AI助手。请根据提供的信息回答问题。"

# 使用默认的AoT-PIKE协议
# 如果需要自定义，可以在这里指定

# 可选：自定义DAG分解协议
dag_decompose_protocol:
  module_path: pikerag.prompts.decomposition.aot_pike
  protocol_name: aot_dag_decomposition_protocol
  template_partial:
    system_prompt: "你是一个擅长问题分解的AI助手。"

# 可选：自定义收缩协议
contract_protocol:
  module_path: pikerag.prompts.decomposition.aot_pike
  protocol_name: aot_contract_protocol
  template_partial:
    system_prompt: "你是一个擅长问题重构的AI助手。"

# 可选：自定义节点回答协议
node_answering_protocol:
  module_path: pikerag.prompts.decomposition.aot_pike
  protocol_name: aot_node_answering_protocol
  template_partial:
    system_prompt: "你是一个擅长回答问题的AI助手。"

# 可选：自定义可解答性检查协议
answerability_check_protocol:
  module_path: pikerag.prompts.decomposition.aot_pike
  protocol_name: aot_answerability_check_protocol
  template_partial:
    system_prompt: "你是一个擅长评估问题的AI助手。"

# 原始问题回答协议（必需）
original_question_answering_protocol:
  module_path: pikerag.prompts.decomposition
  protocol_name: final_qa_protocol

# 集成决策协议（用于比较不同方法的结果）
ensemble_protocol:
  module_path: pikerag.prompts.decomposition.aot_pike
  protocol_name: ensemble_protocol
  template_partial:
    system_prompt: "你是一个擅长评估答案质量的AI助手。"


# LLM Setting
################################################################################
llm_client:
  type: openai
  config:
    model: ${OPENAI_MODEL_NAME}
    temperature: 0.0
    max_tokens: 2048
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0


# Retriever Setting
################################################################################
retriever:
  module_path: pikerag.knowledge_retrievers
  class_name: AoTPikeRetriever
  args:
    retrieve_k: 5
    retrieve_score_threshold: 0.5
    atom_retrieve_k: 3

    # AoT特定配置
    aot_config:
      markov_state_threshold: 0.8
      enable_dynamic_atoms: true
      enable_graph_update: true
      max_dynamic_atoms_per_node: 5

    # 并行处理配置
    enable_parallel: true
    max_parallel_tasks: 5

    vector_store:
      collection_name: hotpotqa_aot_pike
      persist_directory: data/vector_store

      id_document_loading:
        module_path: pikerag.utils.data_loader
        func_name: load_hotpotqa_documents
        args:
          data_path: data/hotpotqa/train.json

      id_atom_loading:
        module_path: pikerag.utils.data_loader
        func_name: load_hotpotqa_atoms
        args:
          data_path: data/hotpotqa/train.json
          atom_tag: question

      embedding_setting:
        type: openai
        config:
          model: ${OPENAI_EMBEDDING_MODEL_NAME}
          batch_size: 32


# Evaluator Setting
################################################################################
evaluator:
  metrics:
    - ExactMatch
    - F1
    - Precision
    - Recall
    - LLM 